# Generated by Django 4.2.16 on 2024-12-05 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gift_creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcreator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gift_creator', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
