# Generated by Django 4.2.16 on 2024-11-28 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0001_initial'),
        ('gift_searches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('to_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gifts.gift')),
                ('to_gift_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gift_searches.giftsearch')),
            ],
        ),
    ]
